eval "$(conda shell.bash hook)" # Necessary to activate conda env, can skip if using no environments
conda activate flower # Necessary to activate conda env, can skip if using no environments
cd Desktop # Change current working directory
export AWS_ACCESS_KEY_ID="" # Id obtained from Care Website
export AWS_SECRET_ACCESS_KEY="" # Key obtained from Care Website
export BUCKET_NAME="empatica-us-east-1-prod-data" # Bucket name obtained from Care Website
export PREFIX_VERSION="v2" # First v2 in the bucket path
export ORGANIZATION_ID="1440" # Organization Id in the Care Website
export PREFIX_PATH_FIRST_UNKNOWN_NUMBER="1" # Number after the Organization ID (probably the supervisor ID)
export PREFIX_PATH_SECOND_UNKNOWN_NUMBER="1" # Number after the supervisor ID 
export DATE_OF_STATS="2024-10-15" # Date in format of YYYY-MM-DD
export PARTICIPANT_INFO="00019-3YK3H151KY" # Participant ID and info generated by Care Website
export RAW_DATA_VERSION="v6" # No idea but it is 6 for now.
export RAW_DATA_SAVE_DIRECTORY='/Users/egemen.isguder/Desktop/latest_raw_data_folder/' # Directory in PC to save raw data
export CSV_SAVE_DIRECTORY='/Users/egemen.isguder/Desktop/csv_files' # Directory in PC to save all csv data
python code.py # Run the code

